#!/bin/bash

PIP=pip3.6 
POST_INSTALL_REQUIREMENTS=/opt/seagate/cortx/utils/conf/requirements.txt

# rpm utility passes additional parameter to indicate whether it is a fresh
# install, un-install or upgrade. For this script un-install or upgrade are
# the valid scenarios. 0 means un-install and 1 means upgrade.
# Remove required packages only when uninstall
if [ $1 == 0 ]
then
    sudo $PIP uninstall --yes -r $POST_INSTALL_REQUIREMENTS
fi
