#!/bin/bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

## Replace <INSTALL_PATH> with cortx installation path. example: /opt/seagate
install_path=<INSTALL_PATH>
cortx_path=$install_path/cortx/
utils_path=$cortx_path/utils

# Take action only in case of un-install
if [ $1 == 0 ]
then
    # Remove the files we have created
    /bin/rm -rf $utils_path
    /bin/rm -f /etc/cortx/cortx.conf
fi
