#!/bin/bash
#
# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

# Get default python3 package installation path
PYCMD=$(cat <<EOF
#!/usr/bin/env python3

import sys
import re
import subprocess
from platform import python_version

python_path = sys.path
py_version = python_version()
py_version = py_version.rsplit('.', 1)[0]
py_tmpl = re.compile(r'^/usr/lib/python(\d*[.,]{0,1}\d*)/site-packages$')

py_install_path = [ path for path in python_path if py_tmpl.match(path) and py_version in path]
print(py_install_path[0])
EOF
)
python_path=$(python3 -c "$PYCMD")
## Replace <INSTALL_PATH> with cortx installation path. example: /opt/seagate
install_path=<INSTALL_PATH>
cortx_path=$install_path/cortx
utils_path=$cortx_path/utils

# Create /etc/cortx. This will be used for storing message_bus.conf file.
/bin/mkdir -p /etc/cortx

# Copy the setup_cli.py as utils_setup.
/bin/mkdir -p $utils_path/bin/
/bin/ln -sf $python_path/cortx/setup/utils_setup.py $utils_path/bin/utils_setup
/bin/chmod +x $utils_path/bin/utils_setup

# Copy the message_bus_server.py as message_bus_server.
/bin/ln -sf $python_path/cortx/utils/utils_server/utils_server.py $utils_path/bin/utils_server
/bin/chmod +x $utils_path/bin/utils_server

# Copy the cortx_support_bundle.py as cortx_support_bundle
/bin/ln -sf $python_path/cortx/support/cortx_support_bundle.py $utils_path/bin/cortx_support_bundle
/bin/chmod +x $utils_path/bin/cortx_support_bundle

# Copy cortx.conf file to /etc/cortx.
[ -f "/etc/cortx/cortx.conf" ] || cp -n $utils_path/conf/cortx.conf.sample /etc/cortx/cortx.conf

# Copy support/utils_support_bundle.py to $utils_path/bin.
/bin/ln -sf $python_path/cortx/support/utils_support_bundle.py $utils_path/bin/utils_support_bundle
/bin/chmod +x $utils_path/bin/utils_support_bundle

# Replace cortx path to support_bundle.yaml.
sed -i -e "s|<CORTX_PATH>|${cortx_path}|g" $utils_path/conf/support_bundle.yaml

# Copy rsyslog config to /etc/rsyslog.d.
[ ! -d "/etc/rsyslog.d" ] && mkdir "/etc/rsyslog.d"
cp -n "$utils_path/conf/0-support_bundle.conf" "/etc/rsyslog.d"
