#!/bin/bash

PACKAGE_LIST="
aiohttp==3.6.1
configparser==4.0.2
confluent-kafka==1.5.0
cryptography==2.8
elasticsearch-dsl==7.3.0
elasticsearch==7.12.0
matplotlib==3.1.3
networkx==2.4
paramiko==2.7.1
python-consul==1.1.0
python-crontab==2.5.1
PyYAML==5.1.2
schematics==2.1.0
toml==0.10.0
cffi==1.14.5
numpy==1.19.2
"
rc=0
for package in $PACKAGE_LIST
do
    pip3 freeze | grep $package > /dev/null
    if [ $? -ne 0 ]; then
       if [ $rc -eq 0 ]; then
           echo "==============================================="
       fi
       echo "Required python package $package is missing"
       rc=-1
    fi
done
if [ $rc -ne 0 ]; then
    echo "Please install above python packages"
    echo "==============================================="
fi
exit $rc 
