#!/bin/bash
#
# Copyright (c) 2021 Seagate Technology LLC and/or its Affiliates
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.

# Value of install_path will be changed at build time
#install_path_placeholder
utils_path=$install_path/cortx/utils

# Create /etc/cortx. This will be used for storing message_bus.conf file
/bin/mkdir -p /etc/cortx

# Copy the setup_cli.py as utils_setup
/bin/mkdir -p $utils_path/bin/
/bin/ln -s /usr/lib/python3.6/site-packages/cortx/setup/utils_setup.py $utils_path/bin/utils_setup
/bin/chmod +x $utils_path/bin//utils_setup

# Copy the message_bus_server.py as message_bus_server
/bin/ln -s /usr/lib/python3.6/site-packages/cortx/utils/utils_server/utils_server.py $utils_path/bin/utils_server
/bin/chmod +x $utils_path/bin/utils_server

# Copy cortx.conf file to /etc/cortx
[ -f "/etc/cortx/cortx.conf" ] || cp -n $utils_path/conf/cortx.conf.sample /etc/cortx/cortx.conf