---

- name: post_install on all component mini-provisioner
  shell: cortx_setup node initialize
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: Discover resources
  shell: cortx_setup resource discover
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: System Resource Manifest
  shell: cortx_setup resource show --manifest --resource_type 'node'
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: Resource Health Check
  shell: cortx_setup resource show --health --resource_type 'node'
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: Node Signature set config-key
  shell: cortx_setup signature set --key LR_SIGNATURE --value HP1_5U84
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
  
- name: Node Signature get config-key
  shell: cortx_setup signature get --key LR_SIGNATURE
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 

- name: Finalize Node Configuration
  shell: cortx_setup node finalize --force
  delegate_to: "{{ item }}"
  with_items: "{{ groups['srvnodes'] }}" 
